# Generated by Django 5.1.2 on 2024-10-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about_session",
            name="user",
        ),
        migrations.RemoveField(
            model_name="about_team_session",
            name="user",
        ),
        migrations.RemoveField(
            model_name="home_client_session",
            name="user",
        ),
        migrations.RemoveField(
            model_name="home_intro_session",
            name="user",
        ),
        migrations.RemoveField(
            model_name="home_team_session",
            name="user",
        ),
        migrations.RemoveField(
            model_name="why_choose_us_session",
            name="user",
        ),
        migrations.AlterField(
            model_name="dashboard_work",
            name="logo",
            field=models.ImageField(upload_to="dashboard_work/intro_session/image/"),
        ),
        migrations.CreateModel(
            name="about_dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        upload_to="dashboard_about/clients_session/image/"
                    ),
                ),
                ("abouttext_about", models.TextField(verbose_name="Description")),
                (
                    "aboutimage",
                    models.ImageField(upload_to="dashboard_about/session/image/"),
                ),
                ("why_choose_ustext", models.TextField(verbose_name="Description")),
                (
                    "why_choose_usimage",
                    models.ImageField(
                        upload_to="dashboard_about/why_choose_us_session/image/"
                    ),
                ),
                ("text_philo", models.TextField(verbose_name="Description")),
                (
                    "image_philo",
                    models.ImageField(upload_to="dashboard_about/session/image_philo/"),
                ),
                ("teamtext", models.TextField(verbose_name="Description")),
                (
                    "teamimage",
                    models.ImageField(upload_to="dashboard_about/team_session/image/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_client_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="home_dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Description")),
                (
                    "video",
                    models.FileField(upload_to="dashboard_home/intro_session/video/"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="dashboard_home/intro_session/image/"),
                ),
                (
                    "clientvideo",
                    models.FileField(upload_to="dashboard_home/client_session/video/"),
                ),
                (
                    "clientimage",
                    models.ImageField(upload_to="dashboard_home/client_session/image/"),
                ),
                ("teamtext", models.TextField(verbose_name="Description")),
                (
                    "teamvideo",
                    models.FileField(upload_to="dashboard_home/team_session/video/"),
                ),
                (
                    "teamimage",
                    models.ImageField(upload_to="dashboard_home/team_session/image/"),
                ),
                ("servicename", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "serviceimage",
                    models.ImageField(
                        upload_to="dashboard_home/service_session/image/"
                    ),
                ),
                (
                    "servicevideo",
                    models.FileField(upload_to="dashboard_home/service_session/video/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="about_clients_session",
        ),
        migrations.DeleteModel(
            name="about_session",
        ),
        migrations.DeleteModel(
            name="about_team_session",
        ),
        migrations.DeleteModel(
            name="home_client_session",
        ),
        migrations.DeleteModel(
            name="home_intro_session",
        ),
        migrations.DeleteModel(
            name="home_team_session",
        ),
        migrations.DeleteModel(
            name="why_choose_us_session",
        ),
    ]
