# Generated by Django 5.1.2 on 2024-10-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_home_dashboard_clientimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home_dashboard",
            name="clientimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_home/client_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="clientvideo",
            field=models.FileField(
                blank=True, null=True, upload_to="dashboard_home/client_session/video/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_home/intro_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="serviceimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_home/service_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="servicevideo",
            field=models.FileField(
                blank=True, null=True, upload_to="dashboard_home/service_session/video/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="teamimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_home/team_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="teamtext",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="teamvideo",
            field=models.FileField(
                blank=True, null=True, upload_to="dashboard_home/team_session/video/"
            ),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="home_dashboard",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="dashboard_home/intro_session/video/"
            ),
        ),
    ]
