# Generated by Django 5.1.2 on 2024-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_home_dashboard_clientimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about_dashboard",
            name="aboutimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_about/session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="abouttext_about",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="dashboard_about/clients_session/image/",
            ),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="image_philo",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_about/session/image_philo/"
            ),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="teamimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_about/team_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="teamtext",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="text_philo",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="why_choose_usimage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="dashboard_about/why_choose_us_session/image/",
            ),
        ),
        migrations.AlterField(
            model_name="about_dashboard",
            name="why_choose_ustext",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="dashboard_work",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_work/intro_session/image/"
            ),
        ),
        migrations.AlterField(
            model_name="dashboard_work",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dashboard_work",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="dashboard_work/intro_session/video/"
            ),
        ),
    ]
