# Generated by Django 5.1.2 on 2024-10-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_team_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team_members",
            options={"ordering": ["-created_at"]},
        ),
    ]
