# Generated by Django 5.1.2 on 2024-10-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_alter_team_members_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dashboard_about/why_choose_us_session/image/",
                    ),
                ),
                (
                    "about_dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_choose_us_images",
                        to="client.about_dashboard",
                    ),
                ),
            ],
        ),
    ]
