# Generated by Django 5.1.2 on 2024-10-27 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_remove_home_dashboard_clientimage_clientimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home_dashboard",
            name="serviceimage",
        ),
        migrations.RemoveField(
            model_name="home_dashboard",
            name="servicename",
        ),
        migrations.RemoveField(
            model_name="home_dashboard",
            name="servicevideo",
        ),
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicename", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "serviceimage",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dashboard_home/service_session/image/",
                    ),
                ),
                (
                    "servicevideo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dashboard_home/service_session/video/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
