# Generated by Django 5.1.2 on 2024-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_remove_home_dashboard_serviceimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_feature_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
