# Generated by Django 5.1.2 on 2024-11-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0014_frontendcontrol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrontendControl",
        ),
        migrations.AlterField(
            model_name="jointeam",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jointeam",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
